### ISSUE TITLE
Can the outline be expanded by default?

### ISSUE THREAD

**Issue by jetorz** [kcyarn/markdown-document#12]
When I write something long,
I always want to have an overview of the document all the time.
But by default,
markdown-document fold all the outline,
so I will have to expand them manually every time.
I wonder if the outline can be set to be expanded by default,
or add a setting to decide by user?

**Comment by jetorz** [comment]
I am totally new on github,
and this is my first public issue,
I do not know if I use issue correctly...

**Comment by kcyarn** [comment]
It's not currently a setting. For now, here's a workaround. Go to your atom folder (on Ubuntu it's .atom). It's the default folder where all your settings and packages are stored. 

You need to edit the markdown-document.less file. Mine's at

`/home/user_name/.atom/packages/markdown-document/styles/markdown-document.less`

Select all. Delete and paste the following:

```
// The ui-variables file is provided by base themes provided by Atom.
//
// See https://github.com/atom/atom-dark-ui/blob/master/styles/ui-variables.less
// for a full listing of what's available.
@import "ui-variables";

.markdown-document {
  .btn {
    padding-top: 1px;
    margin-top: 3px;
    margin-bottom: -3px;
}

.panel-body {
  width: 14vw;
  height: 96vh;
  overflow: auto;
}
ul {
  margin-left: -2em;
}
li {
  list-style: none;
}

li a {
    font-size: 1.1em;
}
li input[type='checkbox'] + label {
    padding-right: 0.7em;
    font-size: 1.1em;
}

li input[type='checkbox']:checked + label:before {
  font-family: "Octicons Regular";
  content:'\f078';
}
li input[type='checkbox'] + label:before {
  font-family: "Octicons Regular";
  content:"\f0a3";
}

li input[type='checkbox'] {
  display: none
}
  li input + label + a + ul
  {
    display: block
  }

li input:checked + label + a + ul
{
  display: none
}

li a:only-child {
    padding-left: 1.3em;
}

}
```
Save the file and restart atom. The headers are now automatically expanded.

**Comment by jetorz** [comment]
Wow, this is amazon.
It works, thx a lot 👍
